### PR TITLE
feat: add ability to include target branch as part of repository name

### LINKED ISSUE #158: Add config option to specify target (base) branch
Up to you of course, but this action looks awesome and I'd like to try it; however, it seems that you can only alter the name of the target branch, and that all PRs are opened on the destination repositories default branch (likely main/master), unless I'm missing something.

Would be great if you could specify the target branch!

### PR DESCRIPTION
**Pull request by oblivioncth**
Introduces optional `@target` suffix for repository names in the configuration that allow specifying a base branch for PRs other than the default.

Closes #158

### CODE REVIEW

**Review by wadackel — COMMENTED** [review]
Hi @oblivioncth, Thank you for your contributing :+1:

The code changes LGTM :heart:
Could you please add a section to the documentation on how to specify the target branch?

**Comment by oblivioncth** [comment]
> Hi @oblivioncth, Thank you for your contributing 👍
> 
> The code changes LGTM ❤️ Could you please add a section to the documentation on how to specify the target branch?

Of course. Silly of me to forget in the first place.

I could change the existing mentions of "branch" in `README.md` to "source branch" in order to further disambiguate them, but I figured less intrusive changes might be preferred, and all-in-all it's not really necessary.

**Review by wadackel — APPROVED** [review]
Thank you for adding it to the document!
LGTM :+1:

**Comment by oblivioncth** [comment]
> Thank you for adding it to the document! LGTM 👍

Awesome. Thanks for the great action!

**Pull request merged**
